server:
  port: 8080

spring:
  application:
    name: news-api
  datasource:
    url: jdbc:postgresql://localhost:5432/news_api
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

